// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.organization-provisioning@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ORGANIZATION_PROVISIONING_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ORGANIZATION_PROVISIONING_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_organization_provisioning { () => { "{\"capability_id\":\"lenso.organization-provisioning@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"get\",\"list\",\"request_cleanup\",\"retry\",\"start\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_organization_provisioning_client { () => { "{\"capability_id\":\"lenso.organization-provisioning@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_organization_provisioning_client { () => { "{\"capability_id\":\"lenso.organization-provisioning@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const GET_OPERATION: &str = "get";
pub const LIST_OPERATION: &str = "list";
pub const REQUEST_CLEANUP_OPERATION: &str = "request_cleanup";
pub const RETRY_OPERATION: &str = "retry";
pub const START_OPERATION: &str = "start";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetRequest {
    #[serde(rename = "provisioning_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provisioning_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetResponse {
    #[serde(rename = "cleanup_completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cleanup_completed_at: Option<Timestamp>,
    #[serde(rename = "cleanup_requested")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cleanup_requested: bool,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<Timestamp>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "last_error")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub last_error: Option<String>,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: Option<String>,
    #[serde(rename = "organization_residue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_residue: bool,
    #[serde(rename = "owner_membership_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub owner_membership_id: Option<String>,
    #[serde(rename = "owner_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub owner_subject: String,
    #[serde(rename = "provisioning_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provisioning_id: String,
    #[serde(rename = "requested_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requested_by: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: GetResponseStatus,
    #[serde(rename = "steps")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub steps: Vec<GetResponseStepsItem>,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetResponseStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "manual_review")]
    ManualReview,
    #[serde(rename = "cleanup_pending")]
    CleanupPending,
    #[serde(rename = "cleanup_running")]
    CleanupRunning,
    #[serde(rename = "cleanup_completed")]
    CleanupCompleted,
    #[serde(rename = "cleanup_failed")]
    CleanupFailed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetResponseStepsItem {
    #[serde(rename = "attempt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt: i64,
    #[serde(rename = "effect_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_id: String,
    #[serde(rename = "external_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub external_id: Option<String>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: GetResponseStepsItemKind,
    #[serde(rename = "last_error")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub last_error: Option<String>,
    #[serde(rename = "ordinal")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub ordinal: i64,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: GetResponseStepsItemStatus,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetResponseStepsItemKind {
    #[serde(rename = "create_organization")]
    CreateOrganization,
    #[serde(rename = "put_entitlement")]
    PutEntitlement,
    #[serde(rename = "revoke_entitlement")]
    RevokeEntitlement,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetResponseStepsItemStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "in_flight")]
    InFlight,
    #[serde(rename = "applied")]
    Applied,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "compensated")]
    Compensated,
    #[serde(rename = "skipped")]
    Skipped,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    ManualResolutionRequired,
    ProvisioningNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRequest {
    #[serde(rename = "cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListResponse {
    #[serde(rename = "items")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub items: Vec<ListResponseItemsItem>,
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListResponseItemsItem {
    #[serde(rename = "cleanup_requested")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cleanup_requested: bool,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "last_error")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub last_error: Option<String>,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: Option<String>,
    #[serde(rename = "organization_residue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_residue: bool,
    #[serde(rename = "owner_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub owner_subject: String,
    #[serde(rename = "provisioning_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provisioning_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ListResponseItemsItemStatus,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListResponseItemsItemStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "manual_review")]
    ManualReview,
    #[serde(rename = "cleanup_pending")]
    CleanupPending,
    #[serde(rename = "cleanup_running")]
    CleanupRunning,
    #[serde(rename = "cleanup_completed")]
    CleanupCompleted,
    #[serde(rename = "cleanup_failed")]
    CleanupFailed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    ManualResolutionRequired,
    ProvisioningNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RequestCleanupRequest {
    #[serde(rename = "evidence")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub evidence: String,
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "provisioning_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provisioning_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RequestCleanupResponse {
    #[serde(rename = "cleanup_completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cleanup_completed_at: Option<Timestamp>,
    #[serde(rename = "cleanup_requested")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cleanup_requested: bool,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<Timestamp>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "last_error")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub last_error: Option<String>,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: Option<String>,
    #[serde(rename = "organization_residue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_residue: bool,
    #[serde(rename = "owner_membership_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub owner_membership_id: Option<String>,
    #[serde(rename = "owner_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub owner_subject: String,
    #[serde(rename = "provisioning_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provisioning_id: String,
    #[serde(rename = "requested_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requested_by: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: RequestCleanupResponseStatus,
    #[serde(rename = "steps")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub steps: Vec<RequestCleanupResponseStepsItem>,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RequestCleanupResponseStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "manual_review")]
    ManualReview,
    #[serde(rename = "cleanup_pending")]
    CleanupPending,
    #[serde(rename = "cleanup_running")]
    CleanupRunning,
    #[serde(rename = "cleanup_completed")]
    CleanupCompleted,
    #[serde(rename = "cleanup_failed")]
    CleanupFailed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RequestCleanupResponseStepsItem {
    #[serde(rename = "attempt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt: i64,
    #[serde(rename = "effect_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_id: String,
    #[serde(rename = "external_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub external_id: Option<String>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: RequestCleanupResponseStepsItemKind,
    #[serde(rename = "last_error")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub last_error: Option<String>,
    #[serde(rename = "ordinal")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub ordinal: i64,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: RequestCleanupResponseStepsItemStatus,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RequestCleanupResponseStepsItemKind {
    #[serde(rename = "create_organization")]
    CreateOrganization,
    #[serde(rename = "put_entitlement")]
    PutEntitlement,
    #[serde(rename = "revoke_entitlement")]
    RevokeEntitlement,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RequestCleanupResponseStepsItemStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "in_flight")]
    InFlight,
    #[serde(rename = "applied")]
    Applied,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "compensated")]
    Compensated,
    #[serde(rename = "skipped")]
    Skipped,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RequestCleanupError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    ManualResolutionRequired,
    ProvisioningNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RetryRequest {
    #[serde(rename = "evidence")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub evidence: String,
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "observed_grant_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub observed_grant_id: Option<String>,
    #[serde(rename = "observed_organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub observed_organization_id: Option<String>,
    #[serde(rename = "observed_owner_membership_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub observed_owner_membership_id: Option<String>,
    #[serde(rename = "provisioning_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provisioning_id: String,
    #[serde(rename = "resolution")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resolution: RetryRequestResolution,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetryRequestResolution {
    #[serde(rename = "retry_failed")]
    RetryFailed,
    #[serde(rename = "confirm_applied")]
    ConfirmApplied,
    #[serde(rename = "confirm_not_applied")]
    ConfirmNotApplied,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RetryResponse {
    #[serde(rename = "cleanup_completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cleanup_completed_at: Option<Timestamp>,
    #[serde(rename = "cleanup_requested")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cleanup_requested: bool,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<Timestamp>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "last_error")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub last_error: Option<String>,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: Option<String>,
    #[serde(rename = "organization_residue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_residue: bool,
    #[serde(rename = "owner_membership_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub owner_membership_id: Option<String>,
    #[serde(rename = "owner_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub owner_subject: String,
    #[serde(rename = "provisioning_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provisioning_id: String,
    #[serde(rename = "requested_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requested_by: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: RetryResponseStatus,
    #[serde(rename = "steps")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub steps: Vec<RetryResponseStepsItem>,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetryResponseStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "manual_review")]
    ManualReview,
    #[serde(rename = "cleanup_pending")]
    CleanupPending,
    #[serde(rename = "cleanup_running")]
    CleanupRunning,
    #[serde(rename = "cleanup_completed")]
    CleanupCompleted,
    #[serde(rename = "cleanup_failed")]
    CleanupFailed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RetryResponseStepsItem {
    #[serde(rename = "attempt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt: i64,
    #[serde(rename = "effect_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_id: String,
    #[serde(rename = "external_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub external_id: Option<String>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: RetryResponseStepsItemKind,
    #[serde(rename = "last_error")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub last_error: Option<String>,
    #[serde(rename = "ordinal")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub ordinal: i64,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: RetryResponseStepsItemStatus,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetryResponseStepsItemKind {
    #[serde(rename = "create_organization")]
    CreateOrganization,
    #[serde(rename = "put_entitlement")]
    PutEntitlement,
    #[serde(rename = "revoke_entitlement")]
    RevokeEntitlement,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetryResponseStepsItemStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "in_flight")]
    InFlight,
    #[serde(rename = "applied")]
    Applied,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "compensated")]
    Compensated,
    #[serde(rename = "skipped")]
    Skipped,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RetryError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    ManualResolutionRequired,
    ProvisioningNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StartRequest {
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "owner_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub owner_subject: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StartResponse {
    #[serde(rename = "cleanup_completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cleanup_completed_at: Option<Timestamp>,
    #[serde(rename = "cleanup_requested")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cleanup_requested: bool,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<Timestamp>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "last_error")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub last_error: Option<String>,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: Option<String>,
    #[serde(rename = "organization_residue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_residue: bool,
    #[serde(rename = "owner_membership_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub owner_membership_id: Option<String>,
    #[serde(rename = "owner_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub owner_subject: String,
    #[serde(rename = "provisioning_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provisioning_id: String,
    #[serde(rename = "requested_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requested_by: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: StartResponseStatus,
    #[serde(rename = "steps")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub steps: Vec<StartResponseStepsItem>,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum StartResponseStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "manual_review")]
    ManualReview,
    #[serde(rename = "cleanup_pending")]
    CleanupPending,
    #[serde(rename = "cleanup_running")]
    CleanupRunning,
    #[serde(rename = "cleanup_completed")]
    CleanupCompleted,
    #[serde(rename = "cleanup_failed")]
    CleanupFailed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StartResponseStepsItem {
    #[serde(rename = "attempt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt: i64,
    #[serde(rename = "effect_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_id: String,
    #[serde(rename = "external_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub external_id: Option<String>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: StartResponseStepsItemKind,
    #[serde(rename = "last_error")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub last_error: Option<String>,
    #[serde(rename = "ordinal")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub ordinal: i64,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: StartResponseStepsItemStatus,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum StartResponseStepsItemKind {
    #[serde(rename = "create_organization")]
    CreateOrganization,
    #[serde(rename = "put_entitlement")]
    PutEntitlement,
    #[serde(rename = "revoke_entitlement")]
    RevokeEntitlement,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum StartResponseStepsItemStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "in_flight")]
    InFlight,
    #[serde(rename = "applied")]
    Applied,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "compensated")]
    Compensated,
    #[serde(rename = "skipped")]
    Skipped,
}

#[derive(Clone, Debug, PartialEq)]
pub enum StartError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    ManualResolutionRequired,
    ProvisioningNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct OrganizationProvisioningGet;
impl RequestCapability for OrganizationProvisioningGet {
    type Request = GetRequest;
    type Response = GetResponse;
    type DomainError = GetError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationProvisioningRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get(context, request)
    }
}

#[derive(Debug)]
pub struct OrganizationProvisioningList;
impl RequestCapability for OrganizationProvisioningList {
    type Request = ListRequest;
    type Response = ListResponse;
    type DomainError = ListError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationProvisioningRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list(context, request)
    }
}

#[derive(Debug)]
pub struct OrganizationProvisioningRequestCleanup;
impl RequestCapability for OrganizationProvisioningRequestCleanup {
    type Request = RequestCleanupRequest;
    type Response = RequestCleanupResponse;
    type DomainError = RequestCleanupError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REQUEST_CLEANUP_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationProvisioningRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).request_cleanup(context, request)
    }
}

#[derive(Debug)]
pub struct OrganizationProvisioningRetry;
impl RequestCapability for OrganizationProvisioningRetry {
    type Request = RetryRequest;
    type Response = RetryResponse;
    type DomainError = RetryError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RETRY_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationProvisioningRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).retry(context, request)
    }
}

#[derive(Debug)]
pub struct OrganizationProvisioningStart;
impl RequestCapability for OrganizationProvisioningStart {
    type Request = StartRequest;
    type Response = StartResponse;
    type DomainError = StartError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != START_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationProvisioningRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).start(context, request)
    }
}

impl serde::Serialize for GetError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::ManualResolutionRequired => serializer.serialize_str("manual_resolution_required"),
            Self::ProvisioningNotFound => serializer.serialize_str("provisioning_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "manual_resolution_required" => Ok(Self::ManualResolutionRequired),
                "provisioning_not_found" => Ok(Self::ProvisioningNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::ManualResolutionRequired => serializer.serialize_str("manual_resolution_required"),
            Self::ProvisioningNotFound => serializer.serialize_str("provisioning_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "manual_resolution_required" => Ok(Self::ManualResolutionRequired),
                "provisioning_not_found" => Ok(Self::ProvisioningNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RequestCleanupError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::ManualResolutionRequired => serializer.serialize_str("manual_resolution_required"),
            Self::ProvisioningNotFound => serializer.serialize_str("provisioning_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RequestCleanupError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "manual_resolution_required" => Ok(Self::ManualResolutionRequired),
                "provisioning_not_found" => Ok(Self::ProvisioningNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RetryError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::ManualResolutionRequired => serializer.serialize_str("manual_resolution_required"),
            Self::ProvisioningNotFound => serializer.serialize_str("provisioning_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RetryError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "manual_resolution_required" => Ok(Self::ManualResolutionRequired),
                "provisioning_not_found" => Ok(Self::ProvisioningNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for StartError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::ManualResolutionRequired => serializer.serialize_str("manual_resolution_required"),
            Self::ProvisioningNotFound => serializer.serialize_str("provisioning_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for StartError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "manual_resolution_required" => Ok(Self::ManualResolutionRequired),
                "provisioning_not_found" => Ok(Self::ProvisioningNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_get_request(value: &GetRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_request(wire: &str) -> Result<GetRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_response(value: &GetResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_response(wire: &str) -> Result<GetResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_error(value: &GetError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_error(wire: &str) -> Result<GetError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_request(value: &ListRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_request(wire: &str) -> Result<ListRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_response(value: &ListResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_response(wire: &str) -> Result<ListResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_error(value: &ListError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_error(wire: &str) -> Result<ListError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_request_cleanup_request(value: &RequestCleanupRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_request_cleanup_request(wire: &str) -> Result<RequestCleanupRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_request_cleanup_response(value: &RequestCleanupResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_request_cleanup_response(wire: &str) -> Result<RequestCleanupResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_request_cleanup_error(value: &RequestCleanupError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_request_cleanup_error(wire: &str) -> Result<RequestCleanupError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_retry_request(value: &RetryRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_retry_request(wire: &str) -> Result<RetryRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_retry_response(value: &RetryResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_retry_response(wire: &str) -> Result<RetryResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_retry_error(value: &RetryError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_retry_error(wire: &str) -> Result<RetryError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_start_request(value: &StartRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_start_request(wire: &str) -> Result<StartRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_start_response(value: &StartResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_start_response(wire: &str) -> Result<StartResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_start_error(value: &StartError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_start_error(wire: &str) -> Result<StartError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoOrganizationProvisioningGetResult {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationProvisioningGetResult for Result<GetResponse, GetError> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationProvisioningGetResult for Result<Result<GetResponse, GetError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationProvisioningGetResult for Result<GetResponse, lenso_plugin_authoring::PluginError<GetError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationProvisioningGetResult for Result<GetResponse, OrganizationProvisioningGetInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationProvisioningGetInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationProvisioningGetInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOrganizationProvisioningListResult {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationProvisioningListResult for Result<ListResponse, ListError> {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationProvisioningListResult for Result<Result<ListResponse, ListError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationProvisioningListResult for Result<ListResponse, lenso_plugin_authoring::PluginError<ListError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationProvisioningListResult for Result<ListResponse, OrganizationProvisioningListInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationProvisioningListInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationProvisioningListInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOrganizationProvisioningRequestCleanupResult {
    fn __lenso_into_result(self) -> Result<Result<RequestCleanupResponse, RequestCleanupError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationProvisioningRequestCleanupResult for Result<RequestCleanupResponse, RequestCleanupError> {
    fn __lenso_into_result(self) -> Result<Result<RequestCleanupResponse, RequestCleanupError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationProvisioningRequestCleanupResult for Result<Result<RequestCleanupResponse, RequestCleanupError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RequestCleanupResponse, RequestCleanupError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationProvisioningRequestCleanupResult for Result<RequestCleanupResponse, lenso_plugin_authoring::PluginError<RequestCleanupError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RequestCleanupResponse, RequestCleanupError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationProvisioningRequestCleanupResult for Result<RequestCleanupResponse, OrganizationProvisioningRequestCleanupInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RequestCleanupResponse, RequestCleanupError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationProvisioningRequestCleanupInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationProvisioningRequestCleanupInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOrganizationProvisioningRetryResult {
    fn __lenso_into_result(self) -> Result<Result<RetryResponse, RetryError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationProvisioningRetryResult for Result<RetryResponse, RetryError> {
    fn __lenso_into_result(self) -> Result<Result<RetryResponse, RetryError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationProvisioningRetryResult for Result<Result<RetryResponse, RetryError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RetryResponse, RetryError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationProvisioningRetryResult for Result<RetryResponse, lenso_plugin_authoring::PluginError<RetryError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RetryResponse, RetryError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationProvisioningRetryResult for Result<RetryResponse, OrganizationProvisioningRetryInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RetryResponse, RetryError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationProvisioningRetryInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationProvisioningRetryInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOrganizationProvisioningStartResult {
    fn __lenso_into_result(self) -> Result<Result<StartResponse, StartError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationProvisioningStartResult for Result<StartResponse, StartError> {
    fn __lenso_into_result(self) -> Result<Result<StartResponse, StartError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationProvisioningStartResult for Result<Result<StartResponse, StartError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<StartResponse, StartError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationProvisioningStartResult for Result<StartResponse, lenso_plugin_authoring::PluginError<StartError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<StartResponse, StartError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationProvisioningStartResult for Result<StartResponse, OrganizationProvisioningStartInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<StartResponse, StartError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationProvisioningStartInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationProvisioningStartInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait OrganizationProvisioningProvider: fmt::Debug + 'static {
    fn get(&self, context: InvocationContext, request: GetRequest) -> NativeRequestFuture<OrganizationProvisioningGet>;
    fn list(&self, context: InvocationContext, request: ListRequest) -> NativeRequestFuture<OrganizationProvisioningList>;
    fn request_cleanup(&self, context: InvocationContext, request: RequestCleanupRequest) -> NativeRequestFuture<OrganizationProvisioningRequestCleanup>;
    fn retry(&self, context: InvocationContext, request: RetryRequest) -> NativeRequestFuture<OrganizationProvisioningRetry>;
    fn start(&self, context: InvocationContext, request: StartRequest) -> NativeRequestFuture<OrganizationProvisioningStart>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_organization_provisioning {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOrganizationProvisioning;
        impl $crate::OrganizationProvisioningProvider for $plugin {
        fn get(&self, context: __LensoNativeSupportOrganizationProvisioning::InvocationContext, request: $crate::GetRequest) -> __LensoNativeSupportOrganizationProvisioning::NativeRequestFuture<$crate::OrganizationProvisioningGet> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationProvisioningGetResult::__lenso_into_result(result)
            })
        }
        fn list(&self, context: __LensoNativeSupportOrganizationProvisioning::InvocationContext, request: $crate::ListRequest) -> __LensoNativeSupportOrganizationProvisioning::NativeRequestFuture<$crate::OrganizationProvisioningList> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationProvisioningListResult::__lenso_into_result(result)
            })
        }
        fn request_cleanup(&self, context: __LensoNativeSupportOrganizationProvisioning::InvocationContext, request: $crate::RequestCleanupRequest) -> __LensoNativeSupportOrganizationProvisioning::NativeRequestFuture<$crate::OrganizationProvisioningRequestCleanup> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::request_cleanup(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationProvisioningRequestCleanupResult::__lenso_into_result(result)
            })
        }
        fn retry(&self, context: __LensoNativeSupportOrganizationProvisioning::InvocationContext, request: $crate::RetryRequest) -> __LensoNativeSupportOrganizationProvisioning::NativeRequestFuture<$crate::OrganizationProvisioningRetry> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::retry(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationProvisioningRetryResult::__lenso_into_result(result)
            })
        }
        fn start(&self, context: __LensoNativeSupportOrganizationProvisioning::InvocationContext, request: $crate::StartRequest) -> __LensoNativeSupportOrganizationProvisioning::NativeRequestFuture<$crate::OrganizationProvisioningStart> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::start(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationProvisioningStartResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct OrganizationProvisioningRequestEndpoint { provider: Rc<dyn OrganizationProvisioningProvider> }

#[derive(Debug)]
pub struct OrganizationProvisioningEndpoint<P: OrganizationProvisioningProvider> { provider: Rc<P>, request_endpoint: OrganizationProvisioningRequestEndpoint }
impl<P: OrganizationProvisioningProvider> OrganizationProvisioningEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn OrganizationProvisioningProvider> = provider.clone();
        Self { provider, request_endpoint: OrganizationProvisioningRequestEndpoint { provider: request_provider } }
    }
}

impl<P: OrganizationProvisioningProvider> NativeRequestEndpoint for OrganizationProvisioningEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        GET_OPERATION,
        LIST_OPERATION,
        REQUEST_CLEANUP_OPERATION,
        RETRY_OPERATION,
        START_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            GET_OPERATION => {
                let Ok(request) = request.downcast::<GetRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_OPERATION => {
                let Ok(request) = request.downcast::<ListRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REQUEST_CLEANUP_OPERATION => {
                let Ok(request) = request.downcast::<RequestCleanupRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).request_cleanup(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RETRY_OPERATION => {
                let Ok(request) = request.downcast::<RetryRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).retry(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            START_OPERATION => {
                let Ok(request) = request.downcast::<StartRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).start(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_organization_provisioning {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::OrganizationProvisioningEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_organization_provisioning {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_organization_provisioning!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct OrganizationProvisioningClient {
    get: NativeRequestHandle<OrganizationProvisioningGet>,
    list: NativeRequestHandle<OrganizationProvisioningList>,
    request_cleanup: NativeRequestHandle<OrganizationProvisioningRequestCleanup>,
    retry: NativeRequestHandle<OrganizationProvisioningRetry>,
    start: NativeRequestHandle<OrganizationProvisioningStart>,
}
impl OrganizationProvisioningClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn get(&self, request: GetRequest) -> Result<GetResponse, OrganizationProvisioningGetInvocationError> {
        self.get.invoke(GET_OPERATION, request).await
            .map_err(OrganizationProvisioningGetInvocationError::Runtime)?
            .map_err(OrganizationProvisioningGetInvocationError::Domain)
    }

    pub async fn get_with_context(&self, context: InvocationContext, request: GetRequest) -> Result<GetResponse, OrganizationProvisioningGetInvocationError> {
        self.get.invoke_with_context(GET_OPERATION, context, request).await
            .map_err(OrganizationProvisioningGetInvocationError::Runtime)?
            .map_err(OrganizationProvisioningGetInvocationError::Domain)
    }

    pub async fn list(&self, request: ListRequest) -> Result<ListResponse, OrganizationProvisioningListInvocationError> {
        self.list.invoke(LIST_OPERATION, request).await
            .map_err(OrganizationProvisioningListInvocationError::Runtime)?
            .map_err(OrganizationProvisioningListInvocationError::Domain)
    }

    pub async fn list_with_context(&self, context: InvocationContext, request: ListRequest) -> Result<ListResponse, OrganizationProvisioningListInvocationError> {
        self.list.invoke_with_context(LIST_OPERATION, context, request).await
            .map_err(OrganizationProvisioningListInvocationError::Runtime)?
            .map_err(OrganizationProvisioningListInvocationError::Domain)
    }

    pub async fn request_cleanup(&self, request: RequestCleanupRequest) -> Result<RequestCleanupResponse, OrganizationProvisioningRequestCleanupInvocationError> {
        self.request_cleanup.invoke(REQUEST_CLEANUP_OPERATION, request).await
            .map_err(OrganizationProvisioningRequestCleanupInvocationError::Runtime)?
            .map_err(OrganizationProvisioningRequestCleanupInvocationError::Domain)
    }

    pub async fn request_cleanup_with_context(&self, context: InvocationContext, request: RequestCleanupRequest) -> Result<RequestCleanupResponse, OrganizationProvisioningRequestCleanupInvocationError> {
        self.request_cleanup.invoke_with_context(REQUEST_CLEANUP_OPERATION, context, request).await
            .map_err(OrganizationProvisioningRequestCleanupInvocationError::Runtime)?
            .map_err(OrganizationProvisioningRequestCleanupInvocationError::Domain)
    }

    pub async fn retry(&self, request: RetryRequest) -> Result<RetryResponse, OrganizationProvisioningRetryInvocationError> {
        self.retry.invoke(RETRY_OPERATION, request).await
            .map_err(OrganizationProvisioningRetryInvocationError::Runtime)?
            .map_err(OrganizationProvisioningRetryInvocationError::Domain)
    }

    pub async fn retry_with_context(&self, context: InvocationContext, request: RetryRequest) -> Result<RetryResponse, OrganizationProvisioningRetryInvocationError> {
        self.retry.invoke_with_context(RETRY_OPERATION, context, request).await
            .map_err(OrganizationProvisioningRetryInvocationError::Runtime)?
            .map_err(OrganizationProvisioningRetryInvocationError::Domain)
    }

    pub async fn start(&self, request: StartRequest) -> Result<StartResponse, OrganizationProvisioningStartInvocationError> {
        self.start.invoke(START_OPERATION, request).await
            .map_err(OrganizationProvisioningStartInvocationError::Runtime)?
            .map_err(OrganizationProvisioningStartInvocationError::Domain)
    }

    pub async fn start_with_context(&self, context: InvocationContext, request: StartRequest) -> Result<StartResponse, OrganizationProvisioningStartInvocationError> {
        self.start.invoke_with_context(START_OPERATION, context, request).await
            .map_err(OrganizationProvisioningStartInvocationError::Runtime)?
            .map_err(OrganizationProvisioningStartInvocationError::Domain)
    }
}

impl CapabilityClient for OrganizationProvisioningClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            get: dependencies.one::<OrganizationProvisioningGet>()?,
            list: dependencies.one::<OrganizationProvisioningList>()?,
            request_cleanup: dependencies.one::<OrganizationProvisioningRequestCleanup>()?,
            retry: dependencies.one::<OrganizationProvisioningRetry>()?,
            start: dependencies.one::<OrganizationProvisioningStart>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for OrganizationProvisioningClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    get: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationProvisioningGet>()?,
                    list: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationProvisioningList>()?,
                    request_cleanup: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationProvisioningRequestCleanup>()?,
                    retry: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationProvisioningRetry>()?,
                    start: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationProvisioningStart>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationProvisioningGetInvocationError {
    Domain(GetError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationProvisioningListInvocationError {
    Domain(ListError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationProvisioningRequestCleanupInvocationError {
    Domain(RequestCleanupError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationProvisioningRetryInvocationError {
    Domain(RetryError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationProvisioningStartInvocationError {
    Domain(StartError),
    Runtime(RuntimeFailure),
}
