// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.organization-provisioning-worker@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ORGANIZATION_PROVISIONING_WORKER_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ORGANIZATION_PROVISIONING_WORKER_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_organization_provisioning_worker { () => { "{\"capability_id\":\"lenso.organization-provisioning-worker@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"process_due\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_organization_provisioning_worker_client { () => { "{\"capability_id\":\"lenso.organization-provisioning-worker@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_organization_provisioning_worker_client { () => { "{\"capability_id\":\"lenso.organization-provisioning-worker@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const PROCESS_DUE_OPERATION: &str = "process_due";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ProcessDueRequest {
    #[serde(rename = "lease_seconds")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_seconds: i64,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ProcessDueResponse {
    #[serde(rename = "claimed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub claimed: i64,
    #[serde(rename = "completed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed: i64,
    #[serde(rename = "failed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failed: i64,
    #[serde(rename = "has_more")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub has_more: bool,
    #[serde(rename = "manual_review")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub manual_review: i64,
    #[serde(rename = "quarantined")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub quarantined: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProcessDueError {
    Forbidden,
    InvalidRequest,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct OrganizationProvisioningWorker;
impl RequestCapability for OrganizationProvisioningWorker {
    type Request = ProcessDueRequest;
    type Response = ProcessDueResponse;
    type DomainError = ProcessDueError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PROCESS_DUE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationProvisioningWorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).process_due(context, request)
    }
}

impl serde::Serialize for ProcessDueError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ProcessDueError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_process_due_request(value: &ProcessDueRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_process_due_request(wire: &str) -> Result<ProcessDueRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_process_due_response(value: &ProcessDueResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_process_due_response(wire: &str) -> Result<ProcessDueResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_process_due_error(value: &ProcessDueError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_process_due_error(wire: &str) -> Result<ProcessDueError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoOrganizationProvisioningWorkerProcessDueResult {
    fn __lenso_into_result(self) -> Result<Result<ProcessDueResponse, ProcessDueError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationProvisioningWorkerProcessDueResult for Result<ProcessDueResponse, ProcessDueError> {
    fn __lenso_into_result(self) -> Result<Result<ProcessDueResponse, ProcessDueError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationProvisioningWorkerProcessDueResult for Result<Result<ProcessDueResponse, ProcessDueError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ProcessDueResponse, ProcessDueError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationProvisioningWorkerProcessDueResult for Result<ProcessDueResponse, lenso_plugin_authoring::PluginError<ProcessDueError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ProcessDueResponse, ProcessDueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationProvisioningWorkerProcessDueResult for Result<ProcessDueResponse, OrganizationProvisioningWorkerInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ProcessDueResponse, ProcessDueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationProvisioningWorkerInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationProvisioningWorkerInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait OrganizationProvisioningWorkerProvider: fmt::Debug + 'static {
    fn process_due(&self, context: InvocationContext, request: ProcessDueRequest) -> NativeRequestFuture<OrganizationProvisioningWorker>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_organization_provisioning_worker {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOrganizationProvisioningWorker;
        impl $crate::OrganizationProvisioningWorkerProvider for $plugin {
        fn process_due(&self, context: __LensoNativeSupportOrganizationProvisioningWorker::InvocationContext, request: $crate::ProcessDueRequest) -> __LensoNativeSupportOrganizationProvisioningWorker::NativeRequestFuture<$crate::OrganizationProvisioningWorker> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::process_due(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationProvisioningWorkerProcessDueResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct OrganizationProvisioningWorkerRequestEndpoint { provider: Rc<dyn OrganizationProvisioningWorkerProvider> }

#[derive(Debug)]
pub struct OrganizationProvisioningWorkerEndpoint<P: OrganizationProvisioningWorkerProvider> { provider: Rc<P>, request_endpoint: OrganizationProvisioningWorkerRequestEndpoint }
impl<P: OrganizationProvisioningWorkerProvider> OrganizationProvisioningWorkerEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn OrganizationProvisioningWorkerProvider> = provider.clone();
        Self { provider, request_endpoint: OrganizationProvisioningWorkerRequestEndpoint { provider: request_provider } }
    }
}

impl<P: OrganizationProvisioningWorkerProvider> NativeRequestEndpoint for OrganizationProvisioningWorkerEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        PROCESS_DUE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            PROCESS_DUE_OPERATION => {
                let Ok(request) = request.downcast::<ProcessDueRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).process_due(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_organization_provisioning_worker {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::OrganizationProvisioningWorkerEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_organization_provisioning_worker {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_organization_provisioning_worker!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct OrganizationProvisioningWorkerClient {
    process_due: NativeRequestHandle<OrganizationProvisioningWorker>,
}
impl OrganizationProvisioningWorkerClient {
    pub fn new(handle: NativeRequestHandle<OrganizationProvisioningWorker>) -> Self {
        Self { process_due: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn process_due(&self, request: ProcessDueRequest) -> Result<ProcessDueResponse, OrganizationProvisioningWorkerInvocationError> {
        self.process_due.invoke(PROCESS_DUE_OPERATION, request).await
            .map_err(OrganizationProvisioningWorkerInvocationError::Runtime)?
            .map_err(OrganizationProvisioningWorkerInvocationError::Domain)
    }

    pub async fn process_due_with_context(&self, context: InvocationContext, request: ProcessDueRequest) -> Result<ProcessDueResponse, OrganizationProvisioningWorkerInvocationError> {
        self.process_due.invoke_with_context(PROCESS_DUE_OPERATION, context, request).await
            .map_err(OrganizationProvisioningWorkerInvocationError::Runtime)?
            .map_err(OrganizationProvisioningWorkerInvocationError::Domain)
    }
}

impl CapabilityClient for OrganizationProvisioningWorkerClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            process_due: dependencies.one::<OrganizationProvisioningWorker>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for OrganizationProvisioningWorkerClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    process_due: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationProvisioningWorker>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationProvisioningWorkerInvocationError {
    Domain(ProcessDueError),
    Runtime(RuntimeFailure),
}
